### ISSUE TITLE
Did you use an LLM or tool like Claude in creating this?

### ISSUE THREAD

**Issue by runvnc** [Faizan711/dungeon-dash#1]
I ask because it looks like it was AI generated through a series of prompts. Which is totally okay of course. I try to use AI to help write code as much as possible these days myself. But I am asking because I was attacked in your HN thread for suggesting it and accused of attempting to hype AI.

**Comment by Faizan711** [comment]
No Jason I didn't use Claude as I don't have any subscription.
I have a free chatgpt account and I take help from it

**Comment by Faizan711** [comment]
Replied you in mail.
